import type { ActivityData } from "../../types/ActivityData";
import dayjs from "dayjs";

export const demoRows: ActivityData[] = [
  {
    id: "1",
    userId: "demoUser",
    date: dayjs("2024-07-08").toISOString(),
    activityName: "Warm-Up",
    activityDuration: 30,
    upperIntensity: 5,
    fingersIntensity: 5,
    lowerIntensity: 2,
    performance: 3,
  },
  {
    id: "2",
    userId: "demoUser",
    date: dayjs("2024-07-08").toISOString(),
    activityName: "PumpCap/AnCap",
    activityDuration: 45,
    upperIntensity: 6,
    fingersIntensity: 6,
    lowerIntensity: 2,
    performance: 4,
  },
  {
    id: "3",
    userId: "demoUser",
    date: dayjs("2024-07-13").toISOString(),
    activityName: "Bouldering",
    activityDuration: 15,
    upperIntensity: 5,
    fingersIntensity: 5,
    lowerIntensity: 2,
    performance: 3,
  },
  {
    id: "4",
    userId: "demoUser",
    date: dayjs("2024-07-13").toISOString(),
    activityName: "Performance",
    activityDuration: 120,
    upperIntensity: 6,
    fingersIntensity: 6,
    lowerIntensity: 2,
    performance: 4,
  },
  {
    id: "5",
    userId: "demoUser",
    date: dayjs("2024-07-15").toISOString(),
    activityName: "Warm-Up",
    activityDuration: 30,
    upperIntensity: 5,
    fingersIntensity: 5,
    lowerIntensity: 2,
    performance: 3,
  },
  {
    id: "6",
    userId: "demoUser",
    date: dayjs("2024-07-15").toISOString(),
    activityName: "Bouldering",
    activityDuration: 90,
    upperIntensity: 8,
    fingersIntensity: 9,
    lowerIntensity: 2,
    performance: 5,
  },
  {
    id: "7",
    userId: "demoUser",
    date: dayjs("2024-07-17").toISOString(),
    activityName: "Warm-Up",
    activityDuration: 45,
    upperIntensity: 5,
    fingersIntensity: 5,
    lowerIntensity: 2,
    performance: 3,
  },
  {
    id: "8",
    userId: "demoUser",
    date: dayjs("2024-07-17").toISOString(),
    activityName: "PumpCap/AnCap",
    activityDuration: 45,
    upperIntensity: 7,
    fingersIntensity: 7,
    lowerIntensity: 2,
    performance: 4,
  },
  {
    id: "9",
    userId: "demoUser",
    date: dayjs("2024-07-20").toISOString(),
    activityName: "Warm-Up",
    activityDuration: 30,
    upperIntensity: 5,
    fingersIntensity: 5,
    lowerIntensity: 2,
    performance: 3,
  },
  {
    id: "10",
    userId: "demoUser",
    date: dayjs("2024-07-20").toISOString(),
    activityName: "Bouldering",
    activityDuration: 120,
    upperIntensity: 7.5,
    fingersIntensity: 7.5,
    lowerIntensity: 2,
    performance: 4,
  },
  {
    id: "11",
    userId: "demoUser",
    date: dayjs("2024-07-22").toISOString(),
    activityName: "Warm-Up",
    activityDuration: 30,
    upperIntensity: 5,
    fingersIntensity: 5,
    lowerIntensity: 2,
    performance: 3,
  },
  {
    id: "12",
    userId: "demoUser",
    date: dayjs("2024-07-22").toISOString(),
    activityName: "Bouldering",
    activityDuration: 60,
    upperIntensity: 8.5,
    fingersIntensity: 7,
    lowerIntensity: 2,
    performance: 5,
  },
  {
    id: "13",
    userId: "demoUser",
    date: dayjs("2024-07-22").toISOString(),
    activityName: "Onsight",
    activityDuration: 15,
    upperIntensity: 8,
    fingersIntensity: 7,
    lowerIntensity: 2,
    performance: 5,
  },
  {
    id: "14",
    userId: "demoUser",
    date: dayjs("2024-07-22").toISOString(),
    activityName: "PumpCap/AnCap",
    activityDuration: 30,
    upperIntensity: 8.5,
    fingersIntensity: 6,
    lowerIntensity: 2,
    performance: 5,
  },
  {
    id: "15",
    userId: "demoUser",
    date: dayjs("2024-07-25").toISOString(),
    activityName: "Warm-Up",
    activityDuration: 30,
    upperIntensity: 5,
    fingersIntensity: 6,
    lowerIntensity: 3,
    performance: 3,
  },
  {
    id: "16",
    userId: "demoUser",
    date: dayjs("2024-07-25").toISOString(),
    activityName: "Bouldering",
    activityDuration: 75,
    upperIntensity: 7.5,
    fingersIntensity: 8.5,
    lowerIntensity: 2,
    performance: 4,
  },
  {
    id: "17",
    userId: "demoUser",
    date: dayjs("2024-07-25").toISOString(),
    activityName: "Strength",
    activityDuration: 15,
    upperIntensity: 0,
    fingersIntensity: 9.5,
    lowerIntensity: 0,
    performance: 5,
  },
];
